// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8277758283516235991),
      name: 'ProductBoxModel',
      lastPropertyId: const obx_int.IdUid(11, 1633331566896269425),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2157536011238288508),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8314389192260273613),
            name: 'productId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 17210902421864521),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6490103131545161520),
            name: 'handle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 922205038779060241),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6260952845064198109),
            name: 'thumbnail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 566586112728947148),
            name: 'isGiftCard',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6100377758065393456),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2723786600222063086),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1790621962708732601),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1633331566896269425),
            name: 'isInWishlist',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4731287340340730454),
      name: 'ProductCategoryBoxModel',
      lastPropertyId: const obx_int.IdUid(7, 2423104388310997711),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4556918281398598521),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8985163328971576081),
            name: 'categoryId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5807120665416761174),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2807882031862501086),
            name: 'handle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7795922007261728612),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5990258894319474299),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2423104388310997711),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 8391483715246859683),
      name: 'ProductCollectionBoxModel',
      lastPropertyId: const obx_int.IdUid(7, 3299614584404711136),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5198965851397501013),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3552565822677413279),
            name: 'collectionId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1840499447851796439),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5956810814699203342),
            name: 'handle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5820818854327270403),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1181166708114549023),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3299614584404711136),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 35185808398094906),
      name: 'ProductTagBoxModel',
      lastPropertyId: const obx_int.IdUid(5, 4724372099765994408),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6625996733000682868),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7295548042318552730),
            name: 'tagId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7053254660530876019),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6367224419518715380),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4724372099765994408),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(4, 35185808398094906),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ProductBoxModel: obx_int.EntityDefinition<ProductBoxModel>(
        model: _entities[0],
        toOneRelations: (ProductBoxModel object) => [],
        toManyRelations: (ProductBoxModel object) => {},
        getId: (ProductBoxModel object) => object.id,
        setId: (ProductBoxModel object, int id) {
          object.id = id;
        },
        objectToFB: (ProductBoxModel object, fb.Builder fbb) {
          final productIdOffset = fbb.writeString(object.productId);
          final titleOffset = fbb.writeString(object.title);
          final handleOffset =
              object.handle == null ? null : fbb.writeString(object.handle!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final thumbnailOffset = object.thumbnail == null
              ? null
              : fbb.writeString(object.thumbnail!);
          final statusOffset =
              object.status == null ? null : fbb.writeString(object.status!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, productIdOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, handleOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addOffset(5, thumbnailOffset);
          fbb.addBool(6, object.isGiftCard);
          fbb.addOffset(7, statusOffset);
          fbb.addInt64(8, object.createdAt?.millisecondsSinceEpoch);
          fbb.addInt64(9, object.updatedAt?.millisecondsSinceEpoch);
          fbb.addBool(10, object.isInWishlist);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final productIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final handleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final thumbnailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final isGiftCardParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final updatedAtParam = updatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
          final isInWishlistParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false);
          final object = ProductBoxModel(
              productId: productIdParam,
              title: titleParam,
              handle: handleParam,
              description: descriptionParam,
              thumbnail: thumbnailParam,
              isGiftCard: isGiftCardParam,
              status: statusParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              isInWishlist: isInWishlistParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ProductCategoryBoxModel: obx_int.EntityDefinition<ProductCategoryBoxModel>(
        model: _entities[1],
        toOneRelations: (ProductCategoryBoxModel object) => [],
        toManyRelations: (ProductCategoryBoxModel object) => {},
        getId: (ProductCategoryBoxModel object) => object.id,
        setId: (ProductCategoryBoxModel object, int id) {
          object.id = id;
        },
        objectToFB: (ProductCategoryBoxModel object, fb.Builder fbb) {
          final categoryIdOffset = fbb.writeString(object.categoryId);
          final nameOffset = fbb.writeString(object.name);
          final handleOffset =
              object.handle == null ? null : fbb.writeString(object.handle!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, handleOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addInt64(5, object.createdAt?.millisecondsSinceEpoch);
          fbb.addInt64(6, object.updatedAt?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final categoryIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final handleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final updatedAtParam = updatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
          final object = ProductCategoryBoxModel(
              categoryId: categoryIdParam,
              name: nameParam,
              handle: handleParam,
              description: descriptionParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ProductCollectionBoxModel: obx_int.EntityDefinition<
            ProductCollectionBoxModel>(
        model: _entities[2],
        toOneRelations: (ProductCollectionBoxModel object) => [],
        toManyRelations: (ProductCollectionBoxModel object) => {},
        getId: (ProductCollectionBoxModel object) => object.id,
        setId: (ProductCollectionBoxModel object, int id) {
          object.id = id;
        },
        objectToFB: (ProductCollectionBoxModel object, fb.Builder fbb) {
          final collectionIdOffset = fbb.writeString(object.collectionId);
          final titleOffset = fbb.writeString(object.title);
          final handleOffset =
              object.handle == null ? null : fbb.writeString(object.handle!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, collectionIdOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, handleOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addInt64(5, object.createdAt?.millisecondsSinceEpoch);
          fbb.addInt64(6, object.updatedAt?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final collectionIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final handleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final updatedAtParam = updatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
          final object = ProductCollectionBoxModel(
              collectionId: collectionIdParam,
              title: titleParam,
              handle: handleParam,
              description: descriptionParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ProductTagBoxModel: obx_int.EntityDefinition<ProductTagBoxModel>(
        model: _entities[3],
        toOneRelations: (ProductTagBoxModel object) => [],
        toManyRelations: (ProductTagBoxModel object) => {},
        getId: (ProductTagBoxModel object) => object.id,
        setId: (ProductTagBoxModel object, int id) {
          object.id = id;
        },
        objectToFB: (ProductTagBoxModel object, fb.Builder fbb) {
          final tagIdOffset = fbb.writeString(object.tagId);
          final valueOffset = fbb.writeString(object.value);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, tagIdOffset);
          fbb.addOffset(2, valueOffset);
          fbb.addInt64(3, object.createdAt?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.updatedAt?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final tagIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final valueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final updatedAtParam = updatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
          final object = ProductTagBoxModel(
              tagId: tagIdParam,
              value: valueParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProductBoxModel] entity fields to define ObjectBox queries.
class ProductBoxModel_ {
  /// see [ProductBoxModel.id]
  static final id =
      obx.QueryIntegerProperty<ProductBoxModel>(_entities[0].properties[0]);

  /// see [ProductBoxModel.productId]
  static final productId =
      obx.QueryStringProperty<ProductBoxModel>(_entities[0].properties[1]);

  /// see [ProductBoxModel.title]
  static final title =
      obx.QueryStringProperty<ProductBoxModel>(_entities[0].properties[2]);

  /// see [ProductBoxModel.handle]
  static final handle =
      obx.QueryStringProperty<ProductBoxModel>(_entities[0].properties[3]);

  /// see [ProductBoxModel.description]
  static final description =
      obx.QueryStringProperty<ProductBoxModel>(_entities[0].properties[4]);

  /// see [ProductBoxModel.thumbnail]
  static final thumbnail =
      obx.QueryStringProperty<ProductBoxModel>(_entities[0].properties[5]);

  /// see [ProductBoxModel.isGiftCard]
  static final isGiftCard =
      obx.QueryBooleanProperty<ProductBoxModel>(_entities[0].properties[6]);

  /// see [ProductBoxModel.status]
  static final status =
      obx.QueryStringProperty<ProductBoxModel>(_entities[0].properties[7]);

  /// see [ProductBoxModel.createdAt]
  static final createdAt =
      obx.QueryDateProperty<ProductBoxModel>(_entities[0].properties[8]);

  /// see [ProductBoxModel.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<ProductBoxModel>(_entities[0].properties[9]);

  /// see [ProductBoxModel.isInWishlist]
  static final isInWishlist =
      obx.QueryBooleanProperty<ProductBoxModel>(_entities[0].properties[10]);
}

/// [ProductCategoryBoxModel] entity fields to define ObjectBox queries.
class ProductCategoryBoxModel_ {
  /// see [ProductCategoryBoxModel.id]
  static final id = obx.QueryIntegerProperty<ProductCategoryBoxModel>(
      _entities[1].properties[0]);

  /// see [ProductCategoryBoxModel.categoryId]
  static final categoryId = obx.QueryStringProperty<ProductCategoryBoxModel>(
      _entities[1].properties[1]);

  /// see [ProductCategoryBoxModel.name]
  static final name = obx.QueryStringProperty<ProductCategoryBoxModel>(
      _entities[1].properties[2]);

  /// see [ProductCategoryBoxModel.handle]
  static final handle = obx.QueryStringProperty<ProductCategoryBoxModel>(
      _entities[1].properties[3]);

  /// see [ProductCategoryBoxModel.description]
  static final description = obx.QueryStringProperty<ProductCategoryBoxModel>(
      _entities[1].properties[4]);

  /// see [ProductCategoryBoxModel.createdAt]
  static final createdAt = obx.QueryDateProperty<ProductCategoryBoxModel>(
      _entities[1].properties[5]);

  /// see [ProductCategoryBoxModel.updatedAt]
  static final updatedAt = obx.QueryDateProperty<ProductCategoryBoxModel>(
      _entities[1].properties[6]);
}

/// [ProductCollectionBoxModel] entity fields to define ObjectBox queries.
class ProductCollectionBoxModel_ {
  /// see [ProductCollectionBoxModel.id]
  static final id = obx.QueryIntegerProperty<ProductCollectionBoxModel>(
      _entities[2].properties[0]);

  /// see [ProductCollectionBoxModel.collectionId]
  static final collectionId =
      obx.QueryStringProperty<ProductCollectionBoxModel>(
          _entities[2].properties[1]);

  /// see [ProductCollectionBoxModel.title]
  static final title = obx.QueryStringProperty<ProductCollectionBoxModel>(
      _entities[2].properties[2]);

  /// see [ProductCollectionBoxModel.handle]
  static final handle = obx.QueryStringProperty<ProductCollectionBoxModel>(
      _entities[2].properties[3]);

  /// see [ProductCollectionBoxModel.description]
  static final description = obx.QueryStringProperty<ProductCollectionBoxModel>(
      _entities[2].properties[4]);

  /// see [ProductCollectionBoxModel.createdAt]
  static final createdAt = obx.QueryDateProperty<ProductCollectionBoxModel>(
      _entities[2].properties[5]);

  /// see [ProductCollectionBoxModel.updatedAt]
  static final updatedAt = obx.QueryDateProperty<ProductCollectionBoxModel>(
      _entities[2].properties[6]);
}

/// [ProductTagBoxModel] entity fields to define ObjectBox queries.
class ProductTagBoxModel_ {
  /// see [ProductTagBoxModel.id]
  static final id =
      obx.QueryIntegerProperty<ProductTagBoxModel>(_entities[3].properties[0]);

  /// see [ProductTagBoxModel.tagId]
  static final tagId =
      obx.QueryStringProperty<ProductTagBoxModel>(_entities[3].properties[1]);

  /// see [ProductTagBoxModel.value]
  static final value =
      obx.QueryStringProperty<ProductTagBoxModel>(_entities[3].properties[2]);

  /// see [ProductTagBoxModel.createdAt]
  static final createdAt =
      obx.QueryDateProperty<ProductTagBoxModel>(_entities[3].properties[3]);

  /// see [ProductTagBoxModel.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<ProductTagBoxModel>(_entities[3].properties[4]);
}
