// This file is expected to be generated by ObjectBox
// We'll define a placeholder until code generation happens
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

/// Placeholder for the ObjectBox Store class
/// This will be replaced by the generated code
class Store {
  Store._();
  
  /// Opens a new instance of the Store
  static Future<Store> create({String? directory}) async {
    return Store._();
  }
}

/// Opens an ObjectBox Store for the current platform
/// This is a placeholder until code generation happens
Future<Store> openStore() async {
  final docsDir = await getApplicationDocumentsDirectory();
  return Store.create(directory: p.join(docsDir.path, "objectbox"));
} 