import 'package:flutter/material.dart';

// Brand Colors
const Color primaryColor = Color(0xFFBF684F);
const Color secondaryColor = Color(0xFFE3BEB6);
const Color tertiaryColor = Color(0xFF5C514F);

// Create material color schemes from brand colors
final ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: primaryColor,
  onPrimary: Colors.white,
  primaryContainer: primaryColor.withOpacity(0.2),
  onPrimaryContainer: primaryColor.withOpacity(0.9),
  secondary: secondaryColor,
  onSecondary: Colors.white,
  secondaryContainer: secondaryColor.withOpacity(0.2),
  onSecondaryContainer: secondaryColor.withOpacity(0.9),
  tertiary: tertiaryColor,
  onTertiary: Colors.white,
  tertiaryContainer: tertiaryColor.withOpacity(0.2),
  onTertiaryContainer: tertiaryColor.withOpacity(0.9),
  error: const Color(0xFFBA1A1A),
  onError: Colors.white,
  errorContainer: const Color(0xFFFFDAD6),
  onErrorContainer: const Color(0xFF410002),
  background: const Color(0xFFFFFBFF),
  onBackground: const Color(0xFF201A19),
  surface: const Color(0xFFFFFBFF),
  onSurface: const Color(0xFF201A19),
  surfaceVariant: const Color(0xFFF5DED6),
  onSurfaceVariant: const Color(0xFF53433F),
  outline: const Color(0xFF85736E),
  outlineVariant: const Color(0xFFD8C2BC),
  shadow: const Color(0xFF000000),
  scrim: const Color(0xFF000000),
  inverseSurface: const Color(0xFF362F2D),
  onInverseSurface: const Color(0xFFFBEEEB),
  inversePrimary: const Color(0xFFFFB59D),
  surfaceTint: primaryColor,
  surfaceContainerLowest: const Color(0xFFFFFFFF),
  surfaceContainerLow: const Color(0xFFFFF1ED),
  surfaceContainer: const Color(0xFFFFF1ED),
  surfaceContainerHigh: const Color(0xFFFFECE7),
  surfaceContainerHighest: const Color(0xFFFAE7E2),
);

final ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: primaryColor.withOpacity(0.8),
  onPrimary: Colors.white,
  primaryContainer: primaryColor.withOpacity(0.3),
  onPrimaryContainer: primaryColor.withOpacity(0.9),
  secondary: secondaryColor.withOpacity(0.8),
  onSecondary: Colors.white,
  secondaryContainer: secondaryColor.withOpacity(0.3),
  onSecondaryContainer: secondaryColor.withOpacity(0.9),
  tertiary: tertiaryColor.withOpacity(0.8),
  onTertiary: Colors.white,
  tertiaryContainer: tertiaryColor.withOpacity(0.3),
  onTertiaryContainer: tertiaryColor.withOpacity(0.9),
  error: const Color(0xFFFFB4AB),
  onError: const Color(0xFF690005),
  errorContainer: const Color(0xFF93000A),
  onErrorContainer: const Color(0xFFFFDAD6),
  background: const Color(0xFF201A19),
  onBackground: const Color(0xFFEDE0DC),
  surface: const Color(0xFF201A19),
  onSurface: const Color(0xFFEDE0DC),
  surfaceVariant: const Color(0xFF53433F),
  onSurfaceVariant: const Color(0xFFD8C2BC),
  outline: const Color(0xFFA08D87),
  outlineVariant: const Color(0xFF53433F),
  shadow: const Color(0xFF000000),
  scrim: const Color(0xFF000000),
  inverseSurface: const Color(0xFFEDE0DC),
  onInverseSurface: const Color(0xFF362F2D),
  inversePrimary: primaryColor,
  surfaceTint: primaryColor.withOpacity(0.8),
  surfaceContainerLowest: const Color(0xFF17120F),
  surfaceContainerLow: const Color(0xFF201A19),
  surfaceContainer: const Color(0xFF241E1D),
  surfaceContainerHigh: const Color(0xFF2E2725),
  surfaceContainerHighest: const Color(0xFF3A322F),
); 